name: sensors_recorder
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sensors: ^0.3.4
  intl: "^0.15.6"  
  rxdart: "^0.18.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
  - family: Markazi Text
    fonts: 
      - asset: fonts/Markazi_Text/MarkaziText-Regular.ttf
  - family: NotoSerif
    fonts: 
      - asset: fonts/Noto_Serif/NotoSerif-Bold.ttf
      - asset: fonts/Noto_Serif/NotoSerif-BoldItalic.ttf
      - asset: fonts/Noto_Serif/NotoSerif-Italic.ttf
      - asset: fonts/Noto_Serif/NotoSerif-Regular.ttf  
  - family: Roboto
    fonts:
      - asset: fonts/Roboto/Roboto-Black.ttf
      - asset: fonts/Roboto/Roboto-BlackItalic.ttf
      - asset: fonts/Roboto/Roboto-Bold.ttf
      - asset: fonts/Roboto/Roboto-BoldItalic.ttf
      - asset: fonts/Roboto/Roboto-Italic.ttf
      - asset: fonts/Roboto/Roboto-Light.ttf
      - asset: fonts/Roboto/Roboto-LightItalic.ttf
      - asset: fonts/Roboto/Roboto-Medium.ttf
      - asset: fonts/Roboto/Roboto-MediumItalic.ttf
      - asset: fonts/Roboto/Roboto-Regular.ttf
      - asset: fonts/Roboto/Roboto-Thin.ttf
      - asset: fonts/Roboto/Roboto-ThinItalic.ttf
  - family: Raleway
    fonts:
      - asset: fonts/Raleway/Raleway-Light.ttf
      - asset: fonts/Raleway/Raleway-Regular.ttf